### ISSUE TITLE
As a user, I need to be able to add or remove movies to list of movies I have watched, so I can see recommendations.

### ISSUE THREAD

**Issue by Joel-Hottinger** [jeffpan602/CineMatch#1]

**Comment by brianxugit** [comment]
**Size: **
**Acceptance Criteria: **

- The user should be able to add a movie to the list of movies they have watched.
- The user should be able to remove a movie from that list.
- The user interface should show the user a list of movies from which they can designate as "have watched"

**Tasks: **

- Design the user's "have watched" list
- Design and develop an interface with the movie database
- Design and develop the interface for displaying and selecting movies
